/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.asti.examenpsicometrico;

/**
 *
 * @author GAMR_
 */
public class Bienvenida extends javax.swing.JPanel {

    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(646, 284));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Intrucciones");

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("1. Encontraran cuatro palabras agrupadas, seleccionar de esas 4, únicamente 2, la que \"Mas\" se parezca a uds. \ny la que \"Menos\" se parezca.\n\n2. Selecciona con un check en la fila de la palabra que mas se parezca en la columna \"M\" (de \"more\" en ingles)\n\n3. Selecciona con un check en la fila de la palabra que menos se parezca en la columna \"L\" (de \"less\" en ingles)\n\n4. Continuar con los grupos de 4 palabras hasta terminar el test.  No dejar ninguna en blanco.\n\n5. Trasladarse a la Pestaña de \"Resultados\", en esta verán cuatro letras \"D\", \"I\", \"S\",\"C\", que son las iniciales\nde: Dominante, Influyente, Estable, Concienzudo.\n\n6. En la gráfica \"Normal\" aparecerá una de todas las letras mas alta, esa es la tendencia de ustedes.\n\n7. Si aparecen dos a la misma altura, apoyarse en las gráficas de \"Motivación\" y de \"Presión\" para determinar \ncual es la tendencia.\n\n8. Aprenderse que letra es la mas dominante en su personalidad, esta puede ser D, I, S, C.\n");
        jTextArea2.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel1)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
