/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.asti.examenpsicometrico;

import java.awt.BorderLayout;
import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.asti.examenpsicometrico.Data.ConexionDB;

/**
 *
 * @author GAMR_
 */
public class Principal extends javax.swing.JInternalFrame {

    private static Principal ventana = null;
    private DatosAlumnoForm datosAlumnoForm;
    private PreguntasForm preguntasForm;
    private TablaPuntuacion tPuntuacion;
    private Component[] components;
    private boolean testIniciado = false;
    private ConexionDB conexion;
    
    /**
     * Creates new form Principal
     */
    private Principal() {
        initComponents();
        
        try {
            ConexionDB.getVentana().setConexion();
            System.out.println("Se pudo");
        } catch (SQLException ex) {
            System.out.println("No se pudo");
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Bienvenida ventanaBienvenida = new Bienvenida();
        ventanaBienvenida.setSize(724, 400);

        contentPanel.removeAll();
        contentPanel.add(ventanaBienvenida, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();
        
        //btnAtras.setEnabled(false);
        btnSiguiente.setEnabled(false);
        btnTerminar.setEnabled(false);
        components = this.buttonsPanel.getComponents();
    }
    
    public static Principal getVentana(){
        if(ventana == null){
            ventana = new Principal();
        }
        
        return ventana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsPanel = new javax.swing.JPanel();
        btnComenzar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();

        buttonsPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnComenzar.setBackground(new java.awt.Color(255, 255, 153));
        btnComenzar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnComenzar.setText("Comenzar");
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(buttonsPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 457, Short.MAX_VALUE)
                        .addComponent(btnSiguiente))
                    .addGroup(buttonsPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTerminar)))
                .addGap(39, 39, 39))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnSiguiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnTerminar)
                .addContainerGap())
        );

        contentPanel.setPreferredSize(new java.awt.Dimension(646, 284));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        this.preguntasForm = new PreguntasForm();
        this.preguntasForm.setSize(724, 400);
        this.datosAlumnoForm = DatosAlumnoForm.getVentana();
        this.datosAlumnoForm.setSize(724, 400);

        contentPanel.removeAll();
        contentPanel.add(this.datosAlumnoForm, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();

        //btnAtras.setEnabled(false);
        btnSiguiente.setEnabled(true);
        btnTerminar.setEnabled(false);
        this.buttonsPanel.remove(this.btnComenzar);
        buttonsPanel.revalidate();
        buttonsPanel.repaint();
    }//GEN-LAST:event_btnComenzarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

        if(this.datosAlumnoForm.getHabilitado()){
            if(this.testIniciado){
                this.preguntasForm.siguiente();
                btnSiguiente.setEnabled(this.preguntasForm.getSiguienteFlag());
                //btnAtras.setEnabled(this.preguntasForm.getAtrasFlag());
                btnTerminar.setEnabled(false);
                if(this.preguntasForm.getPaso() == 23){//numero de pasos
                    btnSiguiente.setEnabled(false);
                    btnTerminar.setEnabled(true);
                }
            }else{
                this.preguntasForm = new PreguntasForm();
                this.preguntasForm.setSize(724, 400);
                contentPanel.removeAll();
                contentPanel.add(this.preguntasForm, BorderLayout.CENTER);
                contentPanel.revalidate();
                contentPanel.repaint();
                this.testIniciado = true;
            }
        }else{
            this.datosAlumnoForm.setAdvertencia();
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        tPuntuacion = TablaPuntuacion.getVentana();
        //tPuntuacion.setDatosAlumno(this.preguntasForm.getDatosAlumno());
        tPuntuacion.setSize(724, 400);
        //this.buttonsPanel.remove(this.btnAtras);
        this.buttonsPanel.remove(this.btnSiguiente);
        this.buttonsPanel.remove(this.btnTerminar);

        contentPanel.removeAll();
        contentPanel.add(tPuntuacion, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel contentPanel;
    // End of variables declaration//GEN-END:variables
}
